# Generated by Django 3.0.4 on 2020-03-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=20, verbose_name='plate Number')),
                ('vehicle_code', models.CharField(max_length=20, verbose_name='vehicle code')),
                ('vehicle_model', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
            ],
        ),
    ]
